
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from create import Ui_create
import sqlite3
from device_access import Ui_device
class Ui_main0(object):
##Message box is an attribute of QtWidgets not QtGui after the latest update thats why its different on the internet    
    def showMessageBox(self,title,message):
        print("")
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()
    def loginCheck(self):
        username = self.lineEdit.text()
        password = self.lineEdit_2.text()
        
        connection = sqlite3.connect("login.db")
        result= connection.execute("SELECT * FROM USERS WHERE USERNAME = ? AND PASSWORD = ?",(username,password))
##The concept behind login check is the query above ^ ,itself acts as an if statement it selects all and fetches only those username and password that are alike
##to our line edit inserted texts and this result is stored in form of rows now if there will be no match then there will exist no row and also
##if there will be irteza named ten times then it will simply have multiple rows
##so in next step we simply count the number of rows i its 0 it means no match more than 0 means user exists doesnt matter how many times he exists
        if(len(result.fetchall())> 0):
            print("User Found")
            self.deviceWindow = QtWidgets.QWidget()
            self.ui = Ui_device()
            self.ui.setupUi(self.deviceWindow)
            self.deviceWindow.show()
        else:
            print("user not found")
            self.showMessageBox('Warning','Invalid Username And Password')
        connection.close()
    def signUpShow(self):
        print("Welcome To Account Creation Panel\n")
        print("Please fill all the details")
        self.signUpWindow = QtWidgets.QDialog()
        self.ui = Ui_create()
        self.ui.setupUi(self.signUpWindow)
        self.signUpWindow.show()
    def signUpCheck(self):
        print("Hi New User ")
        self.signUpShow()
    def setupUi(self, main0):
        main0.setObjectName("main0")
        main0.resize(392, 518)
        self.label = QtWidgets.QLabel(main0)
        self.label.setGeometry(QtCore.QRect(90, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(main0)
        self.label_2.setGeometry(QtCore.QRect(90, 60, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(26)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{color:darkblue}")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(main0)
        self.lineEdit.setGeometry(QtCore.QRect(90, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet(
"QLineEdit {\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: blue;\n"
"}")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(main0)
        self.label_3.setGeometry(QtCore.QRect(90, 200, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(main0)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 230, 211, 31))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: blue;\n"
"}")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(main0)
        self.pushButton.setGeometry(QtCore.QRect(90, 280, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Light")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{ background-color:rgb(84, 190, 255) }\n"
"QPushButton:pressed{background-color: rgb(200,200, 200);border:2px solid darkblue; }\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 2px solid red;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.loginCheck)
        self.pushButton_2 = QtWidgets.QPushButton(main0)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 280, 91, 21))
        self.pushButton_2.clicked.connect(self.signUpCheck)
        font = QtGui.QFont()
        font.setFamily("Myriad Pro Light")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{ background-color:rgb(84, 190, 255) }\n"
"QPushButton:pressed{background-color: rgb(200,200, 200);border:2px solid darkblue; }\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 2px solid red;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(main0)
        self.label_5.setGeometry(QtCore.QRect(250, 300, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(main0)
        self.label_6.setGeometry(QtCore.QRect(200, 320, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.label_6.setStyleSheet("QLabel{color:darkblue}")
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(main0)
        self.label_4.setGeometry(QtCore.QRect(200, 50, 111, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("12022018edu3a_T.jpg"))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(main0)
        self.label_7.setGeometry(QtCore.QRect(20, 340, 47, 13))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(main0)
        self.label_8.setGeometry(QtCore.QRect(50, 180, 281, 281))
        self.label_8.setStyleSheet("QLabel{rgb(222, 226, 255)}")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("rogelio-munoz.png"))
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(main0)
        self.line.setGeometry(QtCore.QRect(20, 470, 351, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(main0)
        self.line_2.setGeometry(QtCore.QRect(13, 30, 20, 441))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(main0)
        self.line_3.setGeometry(QtCore.QRect(20, 20, 351, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(main0)
        self.line_4.setGeometry(QtCore.QRect(360, 30, 20, 451))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.buttonBox = QtWidgets.QDialogButtonBox(main0)
        self.buttonBox.setGeometry(QtCore.QRect(210, 490, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.buttonBox.raise_()

        self.retranslateUi(main0)
        QtCore.QMetaObject.connectSlotsByName(main0)
    
    
    def retranslateUi(self, main0):
        _translate = QtCore.QCoreApplication.translate
        main0.setWindowTitle(_translate("main0", "login_window"))
        self.label.setText(_translate("main0", "Username :"))
        self.label_2.setText(_translate("main0", "LOGIN"))
        self.lineEdit.setWhatsThis(_translate("main0", "Registered Id"))
        self.lineEdit.setPlaceholderText(_translate("main0", "Registered Id?"))
        self.label_3.setText(_translate("main0", "Password :"))
        self.lineEdit_2.setPlaceholderText(_translate("main0", "*********"))
        self.pushButton.setText(_translate("main0", "Sign In"))
        self.pushButton_2.setText(_translate("main0", "Register"))
        self.label_5.setText(_translate("main0", "New User?"))
        self.label_6.setText(_translate("main0", "Forgot Password?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main0 = QtWidgets.QDialog()
    msgBox=QtWidgets.QMessageBox()
    ui = Ui_main0()
    ui.setupUi(main0)
    main0.show()
    sys.exit(app.exec_())

